name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Check C++ formatting
      run: |
        find . -name "*.h" -o -name "*.cpp" | xargs clang-format --dry-run -Werror

  cpp-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --suppress=missingInclude --suppress=unusedFunction src/ include/

  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format code with Black
      run: |
        black .

    - name: Sort imports with isort
      run: |
        isort .

    - name: Run flake8
      run: |
        flake8 .

    - name: Run mypy
      run: |
        mypy . 