name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libarmadillo-dev \
          libopenblas-dev \
          liblapack-dev \
          libarpack2-dev \
          libsuperlu-dev \
          python3-dev \
          python3-pip

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install dependencies in system Python
        sudo pip3 install -r requirements.txt

    - name: Configure CMake
      run: |
        # Create symbolic link for Armadillo
        sudo ln -s /usr/lib/x86_64-linux-gnu/libarmadillo.so.12 /usr/lib/x86_64-linux-gnu/libarmadillo.so
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTING=ON \
          -DPYTHON_EXECUTABLE=$(which python)

    - name: Build
      run: cmake --build build --config Debug -j2

    - name: Run C++ tests
      working-directory: build
      run: ctest --output-on-failure

    - name: Run Python tests with coverage
      run: |
        pip install -e .
        python -m pytest tests/python --cov=pydlf --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 