name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libarmadillo-dev \
          python3-dev \
          python3-pip

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config Debug -j2

    - name: Run C++ tests
      working-directory: build
      run: ctest --output-on-failure

    - name: Run Python tests
      run: |
        pip install -e .
        python -m pytest tests/python 